services:
  - type: web
    name: fetch-assesment-app
    env: node
    plan: free # can be changed to a paid plan
    buildCommand: |
      npm install
      npm run build
    startCommand: node dist/fetch-assesment/server/server.mjs
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
    healthCheckPath: / 